version: '3.5'
services:
  mongo:
    image: mongo:latest
  pycrawler:
    build: .
    environment:
      - MONGO_URL=mongodb://mongo:27017/social_analytics
    env_file:
      - .env
    depends_on:
      - mongo
